import { Poppins, Didact_Gothic } from "next/font/google";
import "./globals.css";

// Import fonts
const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300", "400"] });
const didactGothic = Didact_Gothic({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} ${didactGothic.className}`}>
        {children}
      </body>
    </html>
  );
}
