import { Roboto } from "next/font/google";
import "./globals.css";

// Import fonts
const poppins = Roboto({ subsets: ["latin"], weight: ["100", "300"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {children}
      </body>
    </html>
  );
}
